name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Linting", "Check Formatting"]
    types:
      - completed
    branches:
      - main
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure GCR Credentials
       uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lexicon/forum-backend:latest
          file: ./Dockerfile
          context: .
