name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure GCR Credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lexicon/forum-backend:latest
          file: ./Dockerfile
          context: .
