name: Linting

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  # group runs by <name of the workflow>-<name of job>-<branch name>
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Check linting
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Review linting
        run: pnpm lint
